vim.g.maplocalleader = ","
vim.opt.number = true
vim.opt.mouse = 'a'
vim.opt.ignorecase = false
vim.opt.smartcase = false
vim.opt.hlsearch = false
vim.opt.wrap = true
vim.opt.breakindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.termguicolors = true
vim.opt.completeopt = {'menu', 'menuone', 'noselect'}
